import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../models/models.dart';
import '../services/storage_service.dart';
import '../widgets/app_card.dart';

const expenseCategories=['Alimentação','Transporte','Moradia','Lazer','Educação','Saúde','Compras','Outros'];
const incomeCategories=['Salário','Freelance','Investimentos','Outros'];
class FinanceScreen extends StatefulWidget{const FinanceScreen({super.key});@override State<FinanceScreen> createState()=>_FinanceScreenState();}
class _FinanceScreenState extends State<FinanceScreen>{List<MoneyTransaction> items=[];DateTime month=DateTime(DateTime.now().year,DateTime.now().month);bool loading=true;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{items=(await StorageService.read('finance')).map(MoneyTransaction.fromJson).toList();final now=DateTime.now();for(final x in items){final d=DateTime.tryParse(x.dueDate);if(d!=null&&!x.isPaid&&!x.isCancelled&&d.isBefore(DateTime(now.year,now.month,now.day))){x.paymentStatus='overdue';}}if(mounted)setState(()=>loading=false);}
 Future<void> _save()=>StorageService.write('finance',items.map((e)=>e.toJson()).toList());
 String money(double v)=>'R\$ ${v.toStringAsFixed(2).replaceAll('.',',')}';
 List<MoneyTransaction> monthItems(DateTime d)=>items.where((x)=>x.date.startsWith(DateFormat('yyyy-MM').format(d))&&!x.isCancelled).toList();
 double sum(Iterable<MoneyTransaction> xs,bool income,{bool paid=false})=>xs.where((x)=>x.income==income&&(!paid||x.isPaid)).fold<double>(0.0,(a,x)=>a+x.amount);
 double balance()=>items.where((x)=>x.isPaid&&!x.isCancelled).fold<double>(0.0,(a,x)=>a+(x.income?x.amount:-x.amount));
 Future<void> addSingle(bool income)async{final d=TextEditingController(),a=TextEditingController();String cat=income?'Salário':'Outros';String status='paid';final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,setD)=>AlertDialog(title:Text(income?'Nova entrada':'Nova despesa'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:d,decoration:const InputDecoration(labelText:'Descrição')),TextField(controller:a,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Valor')),DropdownButtonFormField<String>(initialValue:cat,items:(income?incomeCategories:expenseCategories).map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v){if(v!=null)setD(()=>cat=v);}),if(!income)DropdownButtonFormField<String>(initialValue:status,items:const[DropdownMenuItem(value:'paid',child:Text('Pago')),DropdownMenuItem(value:'pending',child:Text('Previsto'))],onChanged:(v){if(v!=null)setD(()=>status=v);})])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Salvar'))])));final v=double.tryParse(a.text.replaceAll(',','.'));if(ok!=true||d.text.trim().isEmpty||v==null||v<=0)return;final date=DateFormat('yyyy-MM-dd').format(DateTime.now());items.add(MoneyTransaction(id:DateTime.now().microsecondsSinceEpoch.toString(),date:date,description:d.text.trim(),category:cat,amount:v,income:income,paymentStatus:income?'paid':status,dueDate:date,paidDate:status=='paid'?date:null));await _save();if(mounted)setState((){});}
 Future<void> addInstallment()async{final d=TextEditingController(),t=TextEditingController(),n=TextEditingController(text:'2');String cat='Outros';final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Compra parcelada'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:d,decoration:const InputDecoration(labelText:'Descrição')),TextField(controller:t,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Valor total')),TextField(controller:n,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Parcelas')),DropdownButtonFormField<String>(initialValue:cat,items:expenseCategories.map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v){if(v!=null)cat=v;})]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Criar'))]));final total=double.tryParse(t.text.replaceAll(',','.'));final count=int.tryParse(n.text);if(ok!=true||d.text.trim().isEmpty||total==null||total<=0||count==null||count<2)return;final group=DateTime.now().microsecondsSinceEpoch.toString();final each=total/count;double used=0;for(var i=1;i<=count;i++){final due=DateTime(DateTime.now().year,DateTime.now().month+i-1,DateTime.now().day);final amount=i==count?double.parse((total-used).toStringAsFixed(2)):double.parse(each.toStringAsFixed(2));used+=amount;final date=DateFormat('yyyy-MM-dd').format(due);final paid=due.isBefore(DateTime.now())||DateUtils.isSameDay(due,DateTime.now());items.add(MoneyTransaction(id:'$group-$i',date:date,description:d.text.trim(),category:cat,amount:amount,income:false,paymentStatus:paid?'paid':'pending',isInstallment:true,installmentGroupId:group,totalInstallments:count,installmentNumber:i,totalAmount:total,installmentAmount:amount,dueDate:date,paidDate:paid?date:null));}await _save();if(mounted)setState((){});}
 Future<void> addRecurring()async{final d=TextEditingController(),a=TextEditingController(),n=TextEditingController(text:'12');String cat='Outros';final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Despesa recorrente'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:d,decoration:const InputDecoration(labelText:'Descrição')),TextField(controller:a,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Valor mensal')),TextField(controller:n,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Meses')),DropdownButtonFormField<String>(initialValue:cat,items:expenseCategories.map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v){if(v!=null)cat=v;})]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Criar'))]));final value=double.tryParse(a.text.replaceAll(',','.'));final count=int.tryParse(n.text);if(ok!=true||d.text.trim().isEmpty||value==null||value<=0||count==null||count<1)return;final group=DateTime.now().microsecondsSinceEpoch.toString();for(var i=0;i<count;i++){final due=DateTime(DateTime.now().year,DateTime.now().month+i,DateTime.now().day);final date=DateFormat('yyyy-MM-dd').format(due);final paid=due.isBefore(DateTime.now())||DateUtils.isSameDay(due,DateTime.now());items.add(MoneyTransaction(id:'r-$group-$i',date:date,description:d.text.trim(),category:cat,amount:value,income:false,paymentStatus:paid?'paid':'pending',isRecurring:true,recurrenceGroupId:group,recurrenceFrequency:'monthly',recurrenceStartDate:date,dueDate:date,paidDate:paid?date:null));}await _save();if(mounted)setState((){});}
 Future<void> menu()async{final v=await showModalBottomSheet<String>(context:context,builder:(c)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(title:const Text('Nova entrada'),onTap:()=>Navigator.pop(c,'in')),ListTile(title:const Text('Nova despesa'),onTap:()=>Navigator.pop(c,'out')),ListTile(title:const Text('Compra parcelada'),onTap:()=>Navigator.pop(c,'inst')),ListTile(title:const Text('Despesa recorrente'),onTap:()=>Navigator.pop(c,'rec'))])));if(v=='in')await addSingle(true);else if(v=='out')await addSingle(false);else if(v=='inst')await addInstallment();else if(v=='rec')await addRecurring();}
 Future<void> toggle(MoneyTransaction x)async{x.paymentStatus=x.isPaid?'pending':'paid';x.paidDate=x.isPaid?null:DateFormat('yyyy-MM-dd').format(DateTime.now());await _save();if(mounted)setState((){});}
 Future<void> remove(MoneyTransaction x)async{items.removeWhere((e)=>e.id==x.id);await _save();if(mounted)setState((){});}
 @override Widget build(BuildContext context){if(loading)return const Center(child:CircularProgressIndicator());final cur=monthItems(month);final inc=sum(cur,true,paid:true),out=sum(cur,false,paid:true);final cats=<String,double>{};for(final x in cur.where((x)=>!x.income)){cats[x.category]=(cats[x.category]??0)+x.amount;}final months=List.generate(6,(i)=>DateTime(month.year,month.month-5+i));return SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[Row(children:[Expanded(child:Text('Financeiro',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.bold))),FilledButton.icon(onPressed:menu,icon:const Icon(Icons.add),label:const Text('Adicionar'))]),AppCard(child:Row(children:[IconButton(onPressed:()=>setState(()=>month=DateTime(month.year,month.month-1)),icon:const Icon(Icons.chevron_left)),Expanded(child:Text(DateFormat('MMMM yyyy','pt_BR').format(month),textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.bold))),IconButton(onPressed:()=>setState(()=>month=DateTime(month.year,month.month+1)),icon:const Icon(Icons.chevron_right))])),Row(children:[Expanded(child:_metric('Entradas realizadas',inc)),Expanded(child:_metric('Despesas realizadas',out))]),Row(children:[Expanded(child:_metric('Saldo atual',balance())),Expanded(child:_metric('Resultado do mês',inc-out))]),AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Previsão e compromissos',style:Theme.of(context).textTheme.titleLarge),Text('Comprometido: ${money(cur.where((x)=>!x.income&&!x.isPaid).fold<double>(0.0,(a,x)=>a+x.amount))}'),Text('Saldo projetado: ${money(sum(cur,true)-sum(cur,false))}')])),AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Entradas x despesas — 6 meses',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:8),SizedBox(height:180,child:CustomPaint(painter:_FinanceChart(months,items,Theme.of(context).colorScheme.primary),child:const SizedBox.expand()))])),if(cats.isNotEmpty)AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Despesas por categoria',style:Theme.of(context).textTheme.titleLarge),for(final e in cats.entries)_cat(e.key,e.value,cats.values.fold<double>(0.0,(a,b)=>a+b))])),const SizedBox(height:8),Text('Movimentações',style:Theme.of(context).textTheme.titleLarge),if(cur.isEmpty)const AppCard(child:Text('Nenhuma movimentação neste mês.')),for(final x in cur)_movement(x)]));}
 Widget _metric(String l,double v)=>AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(money(v),style:const TextStyle(fontWeight:FontWeight.bold)),Text(l,style:Theme.of(context).textTheme.bodySmall)]));
 Widget _cat(String n,double v,double total)=>Padding(padding:const EdgeInsets.only(bottom:10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(n),Text(money(v))]),LinearProgressIndicator(value:total==0?0:v/total)]));
 Widget _movement(MoneyTransaction x)=>AppCard(child:ListTile(contentPadding:EdgeInsets.zero,title:Text(x.description),subtitle:Text('${x.category} • ${x.paymentStatus}${x.isInstallment?' • ${x.installmentNumber}/${x.totalInstallments}':''}${x.isRecurring?' • recorrente':''}'),trailing:PopupMenuButton<String>(onSelected:(v){if(v=='pay')toggle(x);if(v=='delete')remove(x);},itemBuilder:(_)=>const[PopupMenuItem(value:'pay',child:Text('Marcar pago/previsto')),PopupMenuItem(value:'delete',child:Text('Excluir'))])));
}
class _FinanceChart extends CustomPainter{final List<DateTime> months;final List<MoneyTransaction> items;final Color color;_FinanceChart(this.months,this.items,this.color);@override void paint(Canvas c,Size s){final inc=<double>[],out=<double>[];for(final m in months){final k=DateFormat('yyyy-MM').format(m);inc.add(items.where((x)=>x.date.startsWith(k)&&x.income&&x.isPaid&&!x.isCancelled).fold<double>(0.0,(a,x)=>a+x.amount));out.add(items.where((x)=>x.date.startsWith(k)&&!x.income&&x.isPaid&&!x.isCancelled).fold<double>(0.0,(a,x)=>a+x.amount));}final maxV=[...inc,...out].fold<double>(0.0,(a,b)=>a>b?a:b);final range=maxV<=0?1.0:maxV;final p1=Paint()..color=color..strokeWidth=3..style=PaintingStyle.stroke;final p2=Paint()..color=Colors.grey..strokeWidth=3..style=PaintingStyle.stroke;void line(List<double> v,Paint p){final path=Path();for(var i=0;i<v.length;i++){final x=v.length==1?s.width/2:i*s.width/(v.length-1);final y=s.height-20-v[i]/range*(s.height-45);if(i==0){path.moveTo(x,y);}else{path.lineTo(x,y);}}c.drawPath(path,p);}line(inc,p1);line(out,p2);}@override bool shouldRepaint(covariant _FinanceChart old)=>old.months!=months||old.items!=items||old.color!=color;}
