import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:image_picker/image_picker.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/models.dart';
import '../services/ai_food_service.dart';
import '../services/storage_service.dart';
import '../widgets/app_card.dart';

class FoodScreen extends StatefulWidget { const FoodScreen({super.key}); @override State<FoodScreen> createState()=>_FoodScreenState(); }
class _FoodScreenState extends State<FoodScreen> {
  final ai=AiFoodService(); final picker=ImagePicker(); List<Meal> meals=[]; List<WeightEntry> weights=[]; Map<String,double>? goals; bool loading=true;
  String get today=>DateFormat('yyyy-MM-dd').format(DateTime.now());
  @override void initState(){super.initState();_load();}
  Future<void> _load() async { meals=(await StorageService.read('meals')).map(Meal.fromJson).toList(); weights=(await StorageService.read('body_weights')).map(WeightEntry.fromJson).toList()..sort((a,b)=>a.date.compareTo(b.date)); final p=await SharedPreferences.getInstance(); final r=p.getString('nutrition_goals'); if(r!=null){final a=r.split('|');if(a.length==4){goals={'calories':double.tryParse(a[0])??0,'protein':double.tryParse(a[1])??0,'carbs':double.tryParse(a[2])??0,'fat':double.tryParse(a[3])??0};}} if(mounted)setState(()=>loading=false); }
  Future<void> _saveMeals()=>StorageService.write('meals',meals.map((e)=>e.toJson()).toList()); Future<void> _saveWeights()=>StorageService.write('body_weights',weights.map((e)=>e.toJson()).toList());
  Future<void> _saveWeight(double value)async{weights.add(WeightEntry(date:DateTime.now().toIso8601String(),weight:value));weights.sort((a,b)=>a.date.compareTo(b.date));await _saveWeights();}
  Future<void> _weight()async{final c=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('Registrar peso'),content:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(suffixText:'kg')),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Salvar'))]));final v=double.tryParse(c.text.replaceAll(',','.'));c.dispose();if(ok==true&&v!=null&&v>0){await _saveWeight(v);if(mounted)setState((){});}}
  Future<void> _history()async{final rows=[...weights].reversed.toList();await showDialog(context:context,builder:(d)=>AlertDialog(title:const Text('Histórico completo de peso'),content:SizedBox(width:500,height:420,child:rows.isEmpty?const Center(child:Text('Nenhum registro.')):ListView.builder(itemCount:rows.length,itemBuilder:(_,i){final e=rows[i];final dt=DateTime.tryParse(e.date);return ListTile(title:Text('${e.weight.toStringAsFixed(1)} kg'),subtitle:Text(dt==null?e.date:DateFormat('dd/MM/yyyy HH:mm').format(dt)));})),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Fechar'))]));}
  Future<void> _setupGoals()async{final age=TextEditingController(),weight=TextEditingController(),height=TextEditingController();String sex='Masculino',activity='Moderado',objective='Manter peso';final ok=await showDialog<bool>(context:context,builder:(d)=>StatefulBuilder(builder:(d,setD)=>AlertDialog(title:const Text('Metas nutricionais'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:age,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Idade')),TextField(controller:weight,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Peso (kg)')),TextField(controller:height,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Altura (cm)')),DropdownButtonFormField<String>(initialValue:sex,items:['Masculino','Feminino'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v){if(v!=null)setD(()=>sex=v);}),DropdownButtonFormField<String>(initialValue:activity,items:['Sedentário','Levemente ativo','Moderado','Muito ativo','Extremamente ativo'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v){if(v!=null)setD(()=>activity=v);}),DropdownButtonFormField<String>(initialValue:objective,items:['Perder peso','Manter peso','Ganhar peso'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v){if(v!=null)setD(()=>objective=v);})])),actions:[FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Calcular'))]));final a=double.tryParse(age.text),w=double.tryParse(weight.text.replaceAll(',','.')),h=double.tryParse(height.text.replaceAll(',','.'));if(ok!=true||a==null||w==null||h==null||a<=0||w<=0||h<=0)return;const f=<String,double>{'Sedentário':1.2,'Levemente ativo':1.375,'Moderado':1.55,'Muito ativo':1.725,'Extremamente ativo':1.9};final b=sex=='Masculino'?10*w+6.25*h-5*a+5:10*w+6.25*h-5*a-161;final kcal=b*f[activity]!+(objective=='Perder peso'?-400:objective=='Ganhar peso'?300:0);goals={'calories':kcal,'protein':w*2,'fat':kcal*.27/9,'carbs':(kcal-w*2*4-kcal*.27)/4};final p=await SharedPreferences.getInstance();await p.setString('nutrition_goals','${goals!['calories']}|${goals!['protein']}|${goals!['carbs']}|${goals!['fat']}');if(mounted)setState((){});}
  Future<void> _manual()async{final n=TextEditingController(),q=TextEditingController(),k=TextEditingController(),p=TextEditingController(),c=TextEditingController(),f=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('Adicionar alimento'),content:SingleChildScrollView(child:Column(children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Alimento')),TextField(controller:q,decoration:const InputDecoration(labelText:'Quantidade / peso')),TextField(controller:k,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Calorias')),TextField(controller:p,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Proteína (g)')),TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Carboidratos (g)')),TextField(controller:f,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Gorduras (g)'))])),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Adicionar'))]));if(ok==true&&n.text.trim().isNotEmpty){meals.add(Meal(id:DateTime.now().microsecondsSinceEpoch.toString(),date:today,type:'Refeição',food:q.text.trim().isEmpty?n.text.trim():'${n.text.trim()} (${q.text.trim()})',calories:double.tryParse(k.text.replaceAll(',','.'))??0,protein:double.tryParse(p.text.replaceAll(',','.'))??0,carbs:double.tryParse(c.text.replaceAll(',','.'))??0,fat:double.tryParse(f.text.replaceAll(',','.'))??0));await _saveMeals();if(mounted)setState((){});}for(final x in [n,q,k,p,c,f]){x.dispose();}}
  Future<void> _textAI()async{final c=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('Analisar por texto'),content:TextField(controller:c,maxLines:3,decoration:const InputDecoration(hintText:'Ex.: 200g arroz, 150g frango e 2 ovos')),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Analisar'))]));if(ok!=true||c.text.trim().isEmpty){c.dispose();return;}try{await _result(await ai.estimateText(c.text));}catch(e){_message(e.toString());}c.dispose();}
  Future<void> _photo()async{final x=await picker.pickImage(source:ImageSource.camera,imageQuality:80);if(x==null)return;try{await _result(await ai.estimateImage(x.path));}catch(e){_message(e.toString());}}
  Future<void> _result(FoodResult r)async{final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('Estimativa nutricional'),content:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[for(final i in r.items)ListTile(contentPadding:EdgeInsets.zero,title:Text(i.name),subtitle:Text('${i.grams.toStringAsFixed(0)}g • ${i.calories.toStringAsFixed(0)} kcal • P ${i.protein.toStringAsFixed(1)}g • C ${i.carbs.toStringAsFixed(1)}g • G ${i.fat.toStringAsFixed(1)}g')),const Divider(),Text('${r.calories.toStringAsFixed(0)} kcal • P ${r.protein.toStringAsFixed(1)}g • C ${r.carbs.toStringAsFixed(1)}g • G ${r.fat.toStringAsFixed(1)}g')])),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('NÃO CONTAR')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('CONTAR'))]));if(ok==true){meals.add(Meal(id:DateTime.now().microsecondsSinceEpoch.toString(),date:today,type:'Refeição',food:r.items.map((e)=>e.name).join(', '),calories:r.calories,protein:r.protein,carbs:r.carbs,fat:r.fat,source:'ai'));await _saveMeals();if(mounted)setState((){});}}
  void _message(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
  @override Widget build(BuildContext context){if(loading)return const Center(child:CircularProgressIndicator());final tm=meals.where((m)=>m.date==today);final kcal=tm.fold<double>(0,(s,m)=>s+m.calories),pro=tm.fold<double>(0,(s,m)=>s+m.protein),carb=tm.fold<double>(0,(s,m)=>s+m.carbs),fat=tm.fold<double>(0,(s,m)=>s+m.fat);final current=weights.isEmpty?null:weights.last;final chart=weights.length>1?weights.sublist(weights.length>12):<WeightEntry>[];return SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Alimentação',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.bold)),Text('${tm.length} refeição(ões) hoje')])),IconButton(onPressed:_setupGoals,icon:const Icon(Icons.settings_outlined))]),if(goals!=null)AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Metas diárias',style:Theme.of(context).textTheme.titleLarge),_bar('Calorias',kcal,goals!['calories']!,'kcal'),_bar('Proteína',pro,goals!['protein']!,'g'),_bar('Carboidratos',carb,goals!['carbs']!,'g'),_bar('Gorduras',fat,goals!['fat']!,'g')])),AppCard(child:Row(children:[const Icon(Icons.monitor_weight_outlined,size:32),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Peso corporal'),Text(current==null?'—':'${current.weight.toStringAsFixed(1)} kg',style:Theme.of(context).textTheme.titleLarge)])),OutlinedButton(onPressed:_weight,child:const Text('Registrar'))])),if(chart.isNotEmpty)AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Evolução do peso',style:Theme.of(context).textTheme.titleLarge),SizedBox(height:190,child:CustomPaint(painter:_WeightPainter(chart,Theme.of(context).colorScheme.primary),child:const SizedBox.expand())),Row(children:[Expanded(child:Text('Registros: ${weights.length}')),TextButton(onPressed:_history,child:const Text('Ver histórico completo'))])])),if(chart.isEmpty)TextButton.icon(onPressed:_history,icon:const Icon(Icons.history),label:const Text('Ver histórico completo')),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:_manual,icon:const Icon(Icons.add),label:const Text('Manual'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:_textAI,icon:const Icon(Icons.auto_awesome),label:const Text('IA texto'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:_photo,icon:const Icon(Icons.camera_alt),label:const Text('Foto')))]),AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Hoje',style:Theme.of(context).textTheme.titleLarge),if(tm.isEmpty)const Text('Nenhuma refeição registrada.'),for(final m in tm)ListTile(contentPadding:EdgeInsets.zero,title:Text(m.food),subtitle:Text('${m.calories.toStringAsFixed(0)} kcal • P ${m.protein.toStringAsFixed(1)}g • C ${m.carbs.toStringAsFixed(1)}g • G ${m.fat.toStringAsFixed(1)}g'))]))]));}
  Widget _bar(String n,double v,double goal,String unit){final ratio=goal<=0?0.0:(v/goal).clamp(0.0,1.0).toDouble();return Padding(padding:const EdgeInsets.only(top:8),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(n),Text('${v.toStringAsFixed(0)} / ${goal.toStringAsFixed(0)} $unit')]),LinearProgressIndicator(value:ratio)]));}
}
class _WeightPainter extends CustomPainter{final List<WeightEntry> data;final Color color;_WeightPainter(this.data,this.color);@override void paint(Canvas c,Size s){final min=data.map((e)=>e.weight).reduce((a,b)=>a<b?a:b),max=data.map((e)=>e.weight).reduce((a,b)=>a>b?a:b);final range=(max-min).abs()<.01?1.0:max-min;final line=Paint()..color=color..strokeWidth=3..style=PaintingStyle.stroke;final dot=Paint()..color=color;final path=Path();for(var i=0;i<data.length;i++){final x=data.length==1?s.width/2:i*s.width/(data.length-1);final y=s.height-25-((data[i].weight-min)/range)*(s.height-45);if(i==0){path.moveTo(x,y);}else{path.lineTo(x,y);}c.drawCircle(Offset(x,y),4,dot);}c.drawPath(path,line);}@override bool shouldRepaint(covariant _WeightPainter old)=>old.data!=data||old.color!=color;}
