import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../models/models.dart';
import '../services/storage_service.dart';
import '../widgets/app_card.dart';

const muscleOrder=['Peito','Costas','Ombros','Bíceps','Tríceps','Quadríceps','Posterior','Glúteos','Panturrilhas','Abdômen','Outros'];
const weekdays=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'];
const defaultExercises=[['Supino reto','Peito'],['Supino inclinado','Peito'],['Crucifixo máquina','Peito'],['Crossover','Peito'],['Puxada aberta','Costas'],['Remada baixa','Costas'],['Remada unilateral','Costas'],['Desenvolvimento','Ombros'],['Elevação lateral','Ombros'],['Rosca direta','Bíceps'],['Rosca alternada','Bíceps'],['Rosca martelo','Bíceps'],['Tríceps corda','Tríceps'],['Tríceps testa','Tríceps'],['Agachamento','Quadríceps'],['Leg press 45','Quadríceps'],['Cadeira extensora','Quadríceps'],['Mesa flexora','Posterior'],['Stiff','Posterior'],['Hip thrust','Glúteos'],['Panturrilha em pé','Panturrilhas'],['Panturrilha sentado','Panturrilhas'],['Abdominal supra','Abdômen'],['Prancha','Abdômen']];

class GymScreen extends StatefulWidget{const GymScreen({super.key});@override State<GymScreen> createState()=>_GymScreenState();}
class _GymScreenState extends State<GymScreen>{
 List<WorkoutPlan> plans=[];List<List<String>> custom=[];
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{plans=(await StorageService.read('workout_plans')).map(WorkoutPlan.fromJson).toList();custom=(await StorageService.read('exercise_library')).map((e)=>[(e['name']??'').toString(),(e['muscle']??'Outros').toString()]).where((e)=>e[0].isNotEmpty).toList();if(mounted)setState((){});}
 Future<void> _save()=>StorageService.write('workout_plans',plans.map((e)=>e.toJson()).toList());
 List<List<String>> get library{final all=<List<String>>[...defaultExercises,...custom];final seen=<String>{};all.removeWhere((e)=>!seen.add(e[0].toLowerCase()));return all;}
 String _days(List<int> d)=>d.map((x)=>weekdays[x-1].substring(0,3)).join(' • ');
 Future<void> _create({WorkoutPlan? old})async{
  final name=TextEditingController(text:old?.name??'');final selected=<int>{...(old?.weekdays??[DateTime.now().weekday])};final map=<String,List<Exercise>>{};
  if(old!=null){for(final e in old.dayExercises.entries){map[e.key]=e.value.map((x)=>x.copy()).toList();}}
  int day=selected.first;
  final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,ss)=>AlertDialog(title:Text(old==null?'Criar treino':'Editar treino'),content:SizedBox(width:560,child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
   TextField(controller:name,decoration:const InputDecoration(labelText:'Nome do treino',prefixIcon:Icon(Icons.edit_outlined))),const SizedBox(height:16),const Text('Dias da semana',style:TextStyle(fontWeight:FontWeight.bold)),Wrap(spacing:5,children:List.generate(7,(i)=>FilterChip(label:Text(weekdays[i].substring(0,3)),selected:selected.contains(i+1),onSelected:(v){ss((){if(v){selected.add(i+1);day=i+1;}else if(selected.length>1){selected.remove(i+1);if(day==i+1)day=selected.first;}});})) ),
   const SizedBox(height:16),Text('Exercícios de ${weekdays[day-1]}',style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:8),
   ...(map['$day']??[]).map((e)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.fitness_center),title:Text(e.name),subtitle:Text('${e.sets} séries × ${e.reps} reps'),trailing:IconButton(onPressed:()=>ss(()=>map['$day']!.remove(e)),icon:const Icon(Icons.delete_outline)))),
   OutlinedButton.icon(onPressed:()=>_pick(c,map,day,ss),icon:const Icon(Icons.add),label:const Text('Adicionar exercício')),const SizedBox(height:5),const Text('Cada dia pode ter exercícios diferentes.',style:TextStyle(fontSize:12))
  ]))),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Salvar'))])));
  if(ok!=true||name.text.trim().isEmpty)return;final p=old??WorkoutPlan(id:DateTime.now().microsecondsSinceEpoch.toString(),name:name.text.trim(),weekdays:[],dayExercises:{});p.name=name.text.trim();p.weekdays=selected.toList()..sort();p.dayExercises=map;plans.removeWhere((x)=>x.id==p.id);plans.add(p);await _save();if(mounted)setState((){});
 }
 Future<void> _pick(BuildContext parent,Map<String,List<Exercise>> map,int day,StateSetter parentSet)async{
  String search='';String? chosen;int sets=3,reps=10;
  final ok=await showDialog<bool>(context:parent,builder:(c)=>StatefulBuilder(builder:(c,ss){final items=library.where((e)=>e[0].toLowerCase().contains(search.toLowerCase())||e[1].toLowerCase().contains(search.toLowerCase())).toList();return AlertDialog(title:const Text('Todos os exercícios'),content:SizedBox(width:520,height:520,child:Column(children:[TextField(onChanged:(v)=>ss(()=>search=v),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Buscar exercício')),const SizedBox(height:8),Expanded(child:ListView(children:[for(final e in items)RadioListTile<String>(value:e[0],groupValue:chosen,onChanged:(v)=>ss(()=>chosen=v),title:Text(e[0]),subtitle:Text(e[1]))])),Row(children:[Expanded(child:DropdownButtonFormField<int>(initialValue:sets,items:[2,3,4,5].map((x)=>DropdownMenuItem(value:x,child:Text('$x séries'))).toList(),onChanged:(v){if(v!=null)ss(()=>sets=v);},decoration:const InputDecoration(labelText:'Séries'))),const SizedBox(width:8),Expanded(child:DropdownButtonFormField<int>(initialValue:reps,items:[5,6,8,10,12,15,20].map((x)=>DropdownMenuItem(value:x,child:Text('$x reps'))).toList(),onChanged:(v){if(v!=null)ss(()=>reps=v);},decoration:const InputDecoration(labelText:'Reps')))])])),actions:[TextButton(onPressed:()=>_custom(),child:const Text('Novo exercício')),TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:chosen==null?null:()=>Navigator.pop(c,true),child:const Text('Adicionar'))]);}));
  if(ok==true&&chosen!=null){final data=library.firstWhere((e)=>e[0]==chosen);map.putIfAbsent('$day',()=>[]).add(Exercise(id:DateTime.now().microsecondsSinceEpoch.toString(),name:data[0],muscle:data[1],sets:sets,reps:reps));parentSet((){});}
 }
 Future<void> _custom()async{final n=TextEditingController();String muscle='Peito';final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,ss)=>AlertDialog(title:const Text('Novo exercício'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Nome')),DropdownButtonFormField<String>(initialValue:muscle,items:muscleOrder.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v){if(v!=null)ss(()=>muscle=v);},decoration:const InputDecoration(labelText:'Músculo'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Salvar'))])));if(ok==true&&n.text.trim().isNotEmpty){custom.add([n.text.trim(),muscle]);await StorageService.write('exercise_library',custom.map((e)=>{'name':e[0],'muscle':e[1]}).toList());if(mounted)setState((){});}}
 Future<void> _start(WorkoutPlan p,int day)async{final list=p.exercisesFor(day).map((e)=>e.copy()).toList();if(list.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Adicione exercícios para este dia primeiro.')));return;}await Navigator.push(context,MaterialPageRoute(builder:(_)=>WorkoutPlayer(name:p.name,day:day,exercises:list)));}
 @override Widget build(BuildContext context){final today=DateTime.now().weekday;final todays=plans.where((p)=>p.weekdays.contains(today)).toList();return SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(16,14,16,28),children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Academia',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.bold)),Text('${plans.length} treino(s) configurado(s)')])),FilledButton.icon(onPressed:()=>_create(),icon:const Icon(Icons.add),label:const Text('Criar treino'))]),const SizedBox(height:16),if(todays.isNotEmpty)AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Treino de hoje',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),...todays.map((p)=>ListTile(contentPadding:EdgeInsets.zero,title:Text(p.name),subtitle:Text('${p.exercisesFor(today).length} exercícios'),trailing:FilledButton(onPressed:()=>_start(p,today),child:const Text('Iniciar')))])),if(plans.isEmpty)const AppCard(child:Text('Crie seu primeiro treino e escolha os dias e exercícios.')),...plans.map((p)=>AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.fitness_center),const SizedBox(width:8),Expanded(child:Text(p.name,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold))),PopupMenuButton<String>(onSelected:(v){if(v=='edit')_create(old:p);if(v=='delete'){plans.remove(p);_save();setState((){});}},itemBuilder:(c)=>const[PopupMenuItem(value:'edit',child:Text('Editar')),PopupMenuItem(value:'delete',child:Text('Excluir'))])]),Text(_days(p.weekdays)),const SizedBox(height:8),Wrap(spacing:6,runSpacing:6,children:p.weekdays.map((d)=>OutlinedButton.icon(onPressed:()=>_start(p,d),icon:const Icon(Icons.play_arrow,size:18),label:Text(weekdays[d-1]))).toList())])))]));}
}
class WorkoutPlayer extends StatefulWidget{final String name;final int day;final List<Exercise> exercises;const WorkoutPlayer({super.key,required this.name,required this.day,required this.exercises});@override State<WorkoutPlayer> createState()=>_WorkoutPlayerState();}
class _WorkoutPlayerState extends State<WorkoutPlayer>{Future<void> _save()async{await StorageService.write('last_workout_session',[{'date':DateFormat('yyyy-MM-dd').format(DateTime.now()),'name':widget.name,'day':widget.day,'exercises':widget.exercises.map((e)=>e.toJson()).toList()}]);}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.name)),body:ListView(padding:const EdgeInsets.all(16),children:[...widget.exercises.map((e)=>AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(e.name,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),Text('${e.muscle} • ${e.sets} séries × ${e.reps} reps'),...List.generate(e.sets,(i)=>Row(children:[SizedBox(width:60,child:Text('Série ${i+1}')),Expanded(child:TextFormField(initialValue:e.weights[i]==0?'':e.weights[i].toString(),keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Carga kg'),onChanged:(v)=>e.weights[i]=double.tryParse(v.replaceAll(',','.'))??0)),Checkbox(value:e.done[i],onChanged:(v)=>setState(()=>e.done[i]=v??false))]))]))),FilledButton.icon(onPressed:()async{await _save();if(mounted)Navigator.pop(context);},icon:const Icon(Icons.check),label:const Text('Finalizar treino'))]));}
