import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../models/models.dart';
import '../services/storage_service.dart';
import '../widgets/app_card.dart';

const muscleOrder=['Peito','Costas','Ombros','Bíceps','Tríceps','Quadríceps','Posterior','Glúteos','Panturrilhas','Abdômen','Outros'];
const weekdays=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'];
const defaultExercises=<List<String>>[
 ['Supino reto','Peito'],['Supino inclinado','Peito'],['Crucifixo máquina','Peito'],['Crossover','Peito'],['Flexão','Peito'],
 ['Puxada aberta','Costas'],['Puxada fechada','Costas'],['Remada baixa','Costas'],['Remada cavalinho','Costas'],['Remada unilateral','Costas'],['Pullover','Costas'],
 ['Desenvolvimento','Ombros'],['Elevação lateral','Ombros'],['Elevação frontal','Ombros'],['Crucifixo inverso','Ombros'],
 ['Rosca direta','Bíceps'],['Rosca alternada','Bíceps'],['Rosca Scott','Bíceps'],['Rosca martelo','Bíceps'],
 ['Tríceps corda','Tríceps'],['Tríceps testa','Tríceps'],['Tríceps francês','Tríceps'],['Mergulho','Tríceps'],
 ['Agachamento','Quadríceps'],['Leg press 45','Quadríceps'],['Cadeira extensora','Quadríceps'],['Afundo','Quadríceps'],
 ['Mesa flexora','Posterior'],['Cadeira flexora','Posterior'],['Stiff','Posterior'],['Terra romeno','Posterior'],
 ['Hip thrust','Glúteos'],['Elevação pélvica','Glúteos'],['Abdução','Glúteos'],['Panturrilha em pé','Panturrilhas'],['Panturrilha sentado','Panturrilhas'],
 ['Abdominal supra','Abdômen'],['Abdominal infra','Abdômen'],['Prancha','Abdômen'],['Elevação de pernas','Abdômen']];

class GymScreen extends StatefulWidget{const GymScreen({super.key});@override State<GymScreen> createState()=>_GymScreenState();}
class _GymScreenState extends State<GymScreen>{
 List<WorkoutPlan> plans=[]; List<List<String>> custom=[];
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{final raw=await StorageService.read('workout_plans'); final old=await StorageService.read('workouts'); final rc=await StorageService.read('exercise_library'); plans=raw.map(WorkoutPlan.fromJson).toList();
   if(plans.isEmpty&&old.isNotEmpty){final map=<String,WorkoutPlan>{}; for(final w in old.map(Workout.fromJson)){final p=map.putIfAbsent(w.name,()=>WorkoutPlan(id:w.name.hashCode.toString(),name:w.name,weekdays:[],dayExercises:{})); if(!p.weekdays.contains(w.weekday))p.weekdays.add(w.weekday); p.dayExercises['${w.weekday}']=w.exercises; } plans=map.values.toList(); await _save();}
   custom=rc.map((e)=>[(e['name']??'').toString(),(e['muscle']??'Outros').toString()]).where((e)=>e[0].isNotEmpty).toList();if(mounted)setState((){});}
 Future<void> _save()=>StorageService.write('workout_plans',plans.map((p)=>p.toJson()).toList());
 List<List<String>> get library{final all=<List<String>>[...defaultExercises,...custom];final seen=<String>{};all.removeWhere((e)=>!seen.add('${e[1]}::${e[0].toLowerCase()}'));all.sort((a,b){int ai=muscleOrder.indexOf(a[1]),bi=muscleOrder.indexOf(b[1]);ai=ai<0?999:ai;bi=bi<0?999:bi;return ai==bi?a[0].toLowerCase().compareTo(b[0].toLowerCase()):ai.compareTo(bi);});return all;}
 String _days(List<int> days)=>days.map((d)=>weekdays[d-1].substring(0,3)).join(' • ');
 Future<void> _createPlan({WorkoutPlan? existing})async{final name=TextEditingController(text:existing?.name??'');final selected=<int>{...(existing?.weekdays??[]) }; if(selected.isEmpty)selected.add(DateTime.now().weekday);final dayExercises=<String,List<Exercise>>{}; if(existing!=null)for(final e in existing.dayExercises.entries)dayExercises[e.key]=e.value.map((x)=>x.copy()).toList();
   int active=selected.first; final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,ss)=>AlertDialog(title:Text(existing==null?'Criar treino':'Editar treino'),content:SizedBox(width:560,child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Nome do treino',prefixIcon:Icon(Icons.edit_outlined))),const SizedBox(height:18),Text('Dias da semana',style:Theme.of(c).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:8),Wrap(spacing:6,children:List.generate(7,(i)=>FilterChip(label:Text(weekdays[i].substring(0,3)),selected:selected.contains(i+1),onSelected:(v)=>ss((){if(v){selected.add(i+1);active=i+1;}else if(selected.length>1){selected.remove(i+1);if(active==i+1)active=selected.first;}})))),const SizedBox(height:18),Row(children:[Expanded(child:Text('Exercícios de ${weekdays[active-1]}',style:Theme.of(c).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold))),Text('${dayExercises['$active']?.length??0}')]),const SizedBox(height:8),...(dayExercises['$active']??[]).map((e)=>Card(child:ListTile(leading:const Icon(Icons.fitness_center),title:Text(e.name),subtitle:Text('${e.muscle} • ${e.sets} séries × ${e.reps} reps'),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()=>ss(()=>dayExercises['$active']!.remove(e))))),),const SizedBox(height:8),OutlinedButton.icon(onPressed:()=>_pickExercise(c,dayExercises,active,ss),icon:const Icon(Icons.add),label:const Text('Adicionar exercício')),const SizedBox(height:4),const Text('Você pode configurar exercícios diferentes para cada dia do mesmo treino.',style:TextStyle(fontSize:12))]))),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Salvar treino'))])));
   if(ok!=true||name.text.trim().isEmpty)return;final cleanDays=selected.toList()..sort();final p=existing??WorkoutPlan(id:DateTime.now().microsecondsSinceEpoch.toString(),name:name.text.trim(),weekdays:cleanDays,dayExercises:{});p.name=name.text.trim();p.weekdays=cleanDays;p.dayExercises=dayExercises;plans.removeWhere((x)=>x.id==p.id);plans.add(p);await _save();if(mounted)setState((){});}
 Future<void> _pickExercise(BuildContext parent,Map<String,List<Exercise>> dayExercises,int day,StateSetter ss)async{String search='';String? selected;int sets=3,reps=10;final ok=await showDialog<bool>(context:parent,builder:(c)=>StatefulBuilder(builder:(c,sss){final filtered=library.where((e)=>search.isEmpty||e[0].toLowerCase().contains(search.toLowerCase())||e[1].toLowerCase().contains(search.toLowerCase())).toList();return AlertDialog(title:const Text('Todos os exercícios'),content:SizedBox(width:520,height:540,child:Column(children:[TextField(decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Buscar por exercício ou músculo'),onChanged:(v)=>sss(()=>search=v)),const SizedBox(height:8),Expanded(child:ListView(children:[for(final group in muscleOrder)...[Padding(padding:const EdgeInsets.only(top:8,bottom:2),child:Align(alignment:Alignment.centerLeft,child:Text(group,style:const TextStyle(fontWeight:FontWeight.bold)))),...filtered.where((e)=>e[1]==group).map((e)=>RadioListTile<String>(dense:true,value:e[0],groupValue:selected,title:Text(e[0]),onChanged:(v)=>sss(()=>selected=v)))]])),Row(children:[Expanded(child:DropdownButtonFormField<int>(initialValue:sets,items:[2,3,4,5].map((x)=>DropdownMenuItem(value:x,child:Text('$x séries'))).toList(),onChanged:(v){if(v!=null)sss(()=>sets=v);},decoration:const InputDecoration(labelText:'Séries'))),const SizedBox(width:8),Expanded(child:DropdownButtonFormField<int>(initialValue:reps,items:[5,6,8,10,12,15,20].map((x)=>DropdownMenuItem(value:x,child:Text('$x reps'))).toList(),onChanged:(v){if(v!=null)sss(()=>reps=v);},decoration:const InputDecoration(labelText:'Reps')))])])),actions:[TextButton(onPressed:()=>_addCustomExercise(),child:const Text('Novo exercício')),TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancelar')),FilledButton(onPressed:selected==null?null:()=>Navigator.pop(c,true),child:const Text('Adicionar'))]);}));
   if(ok==true&&selected!=null){final e=library.firstWhere((x)=>x[0]==selected);dayExercises.putIfAbsent('$day',()=>[]).add(Exercise(id:DateTime.now().microsecondsSinceEpoch.toString(),name:e[0],muscle:e[1],sets:sets,reps:reps));ss((){});}}
 Future<void> _addCustomExercise()async{final n=TextEditingController();String muscle='Peito';final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,ss)=>AlertDialog(title:const Text('Novo exercício'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Nome')),DropdownButtonFormField<String>(initialValue:muscle,items:muscleOrder.map((m)=>DropdownMenuItem(value:m,child:Text(m))).toList(),onChanged:(v){if(v!=null)ss(()=>muscle=v);},decoration:const InputDecoration(labelText:'Músculo'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Salvar'))])));if(ok==true&&n.text.trim().isNotEmpty){custom.add([n.text.trim(),muscle]);await StorageService.write('exercise_library',custom.map((e)=>{'name':e[0],'muscle':e[1]}).toList());if(mounted)setState((){});}}
 Future<void> _start(WorkoutPlan p,int day)async{final exercises=p.exercisesFor(day).map((e)=>e.copy()).toList();if(exercises.isEmpty){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Adicione exercícios para este dia primeiro.')));return;}await Navigator.push(context,MaterialPageRoute(builder:(_)=>WorkoutPlayer(name:p.name,day:day,exercises:exercises,onSave:()async{await StorageService.write('workout_sessions',[]); })));}
 @override Widget build(BuildContext context){final today=DateTime.now().weekday;final todays=plans.where((p)=>p.weekdays.contains(today)).toList();return SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(16,12,16,28),children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Academia',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.bold)),Text('${plans.length} treino(s) configurado(s)',style:Theme.of(context).textTheme.bodyMedium)])),FilledButton.icon(onPressed:()=>_createPlan(),icon:const Icon(Icons.add),label:const Text('Criar treino'))]),const SizedBox(height:18),if(todays.isNotEmpty)AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Treino de hoje',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:8),...todays.map((p)=>ListTile(contentPadding:EdgeInsets.zero,leading:const CircleAvatar(child:Icon(Icons.play_arrow)),title:Text(p.name),subtitle:Text('${p.exercisesFor(today).length} exercícios'),trailing:FilledButton(onPressed:()=>_start(p,today),child:const Text('Iniciar')))])),if(plans.isEmpty)AppCard(child:Column(children:[const Icon(Icons.fitness_center,size:42),const SizedBox(height:8),const Text('Crie sua primeira divisão de treino.',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:4),const Text('Um treino pode ter vários dias e cada dia pode ter seus próprios exercícios.')])),...plans.map((p)=>AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.fitness_center),const SizedBox(width:10),Expanded(child:Text(p.name,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold))),PopupMenuButton<String>(onSelected:(v){if(v=='edit')_createPlan(existing:p);if(v=='delete'){setState(()=>plans.remove(p));_save();}},itemBuilder:(_)=>const[PopupMenuItem(value:'edit',child:Text('Editar treino')),PopupMenuItem(value:'delete',child:Text('Excluir treino'))])]),Text(_days(p.weekdays),style:Theme.of(context).textTheme.bodyMedium),const SizedBox(height:12),Wrap(spacing:8,runSpacing:8,children:p.weekdays.map((d)=>OutlinedButton.icon(onPressed:()=>_start(p,d),icon:const Icon(Icons.play_arrow,size:18),label:Text(weekdays[d-1]))).toList()),const SizedBox(height:10),Text('${p.dayExercises.values.fold<int>(0,(s,e)=>s+e.length)} exercícios configurados',style:Theme.of(context).textTheme.bodySmall)]))),]));}
}

class WorkoutPlayer extends StatefulWidget{final String name;final int day;final List<Exercise> exercises;final Future<void> Function() onSave;const WorkoutPlayer({super.key,required this.name,required this.day,required this.exercises,required this.onSave});@override State<WorkoutPlayer> createState()=>_WorkoutPlayerState();}
class _WorkoutPlayerState extends State<WorkoutPlayer>{
 Future<void> _save(){return StorageService.write('last_workout_session',[{'date':DateFormat('yyyy-MM-dd').format(DateTime.now()),'name':widget.name,'day':widget.day,'exercises':widget.exercises.map((e)=>e.toJson()).toList()}]);}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.name),subtitle:Text(weekdays[widget.day-1])),body:ListView(padding:const EdgeInsets.all(16),children:[...widget.exercises.map((e)=>AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(e.name,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),Text('${e.muscle} • ${e.sets} séries × ${e.reps} reps'),const SizedBox(height:8),...List.generate(e.sets,(i)=>Row(children:[SizedBox(width:68,child:Text('Série ${i+1}')),Expanded(child:TextFormField(initialValue:e.weights[i]==0?'':e.weights[i].toString(),keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Carga (kg)'),onChanged:(v)=>e.weights[i]=double.tryParse(v.replaceAll(',','.'))??0)),Checkbox(value:e.done[i],onChanged:(v)=>setState(()=>e.done[i]=v??false))]))]))),FilledButton.icon(onPressed:()async{await _save();if(mounted)Navigator.pop(context);},icon:const Icon(Icons.check),label:const Text('Finalizar treino'))]));}
