import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../models/models.dart';
import '../services/storage_service.dart';
import '../widgets/app_card.dart';

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> {
  List<AgendaEvent> events=[]; List<Meal> meals=[]; List<MoneyTransaction> money=[]; List<WorkoutPlan> plans=[]; bool loading=true;
  @override void initState(){super.initState();_load();}
  Future<void> _load() async { try { events=(await StorageService.read('agenda')).map(AgendaEvent.fromJson).toList(); meals=(await StorageService.read('meals')).map(Meal.fromJson).toList(); money=(await StorageService.read('finance')).map(MoneyTransaction.fromJson).toList(); plans=(await StorageService.read('workout_plans')).map(WorkoutPlan.fromJson).toList(); } catch(_){events=[];meals=[];money=[];plans=[];} if(mounted)setState(()=>loading=false); }
  double _food(Iterable<Meal> xs,int type)=>xs.fold(0.0,(s,e)=>s+(type==0?e.calories:type==1?e.protein:type==2?e.carbs:e.fat));
  double _cash(Iterable<MoneyTransaction> xs,bool income,{bool paid=false})=>xs.where((e)=>e.income==income&&(!paid||e.isPaid)&&!e.isCancelled).fold(0.0,(s,e)=>s+e.amount);
  double _committed(DateTime m)=>money.where((e)=>e.date.startsWith(DateFormat('yyyy-MM').format(m))&&!e.income&&!e.isPaid&&!e.isCancelled).fold(0.0,(s,e)=>s+e.amount);
  @override Widget build(BuildContext context){if(loading)return const Center(child:CircularProgressIndicator()); final now=DateTime.now(); final today=DateFormat('yyyy-MM-dd').format(now); final month=DateFormat('yyyy-MM').format(now); final todayEvents=events.where((e)=>e.date==today).toList()..sort((a,b)=>a.start.compareTo(b.start)); final todayMeals=meals.where((e)=>e.date==today); final todayPlans=plans.where((e)=>e.weekdays.contains(now.weekday)&&e.exercisesFor(now.weekday).isNotEmpty).toList(); final monthMoney=money.where((e)=>e.date.startsWith(month)); final income=_cash(monthMoney,true,paid:true), expense=_cash(monthMoney,false,paid:true); final balance=_cash(money,true,paid:true)-_cash(money,false,paid:true); final next=DateTime(now.year,now.month+1); final nextIncome=_cash(money.where((e)=>e.date.startsWith(DateFormat('yyyy-MM').format(next))),true); final nextExpense=money.where((e)=>e.date.startsWith(DateFormat('yyyy-MM').format(next))&&!e.income&&!e.isCancelled).fold(0.0,(s,e)=>s+e.amount);
    return SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[Text('Olá! 👋',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.bold)),Text(DateFormat("EEEE, dd 'de' MMMM",'pt_BR').format(now)),const SizedBox(height:16),_card(context,'Resumo de hoje',Row(children:[_counter(context,Icons.event_outlined,'Compromissos',todayEvents.length.toString()),_counter(context,Icons.fitness_center,'Treinos',todayPlans.length.toString()),_counter(context,Icons.restaurant_outlined,'Refeições',todayMeals.length.toString())])),_card(context,'Próximos compromissos',todayEvents.isEmpty?const Text('Nada agendado hoje.'):Column(children:todayEvents.take(4).map((e)=>ListTile(contentPadding:EdgeInsets.zero,leading:const CircleAvatar(child:Icon(Icons.event)),title:Text(e.title),subtitle:Text('${e.start} • ${e.end}')).toList())),_card(context,'Alimentação de hoje',Row(children:[_stat(context,_food(todayMeals,0).toStringAsFixed(0),'kcal'),_stat(context,'${_food(todayMeals,1).toStringAsFixed(0)}g','proteína'),_stat(context,'${_food(todayMeals,2).toStringAsFixed(0)}g','carboidratos'),_stat(context,'${_food(todayMeals,3).toStringAsFixed(0)}g','gorduras')])),_card(context,'Financeiro do mês',Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[_stat(context,'R\$ ${income.toStringAsFixed(0)}','entradas'),_stat(context,'R\$ ${expense.toStringAsFixed(0)}','despesas'),_stat(context,'R\$ ${(income-expense).toStringAsFixed(0)}','resultado')]),const SizedBox(height:8),Text('Saldo atual: R\$ ${balance.toStringAsFixed(2)}'),Text('Comprometido no mês: R\$ ${_committed(now).toStringAsFixed(2)}'),Text('Próximo mês previsto: R\$ ${(nextIncome-nextExpense).toStringAsFixed(2)}')]))])); }
  Widget _card(BuildContext context,String title,Widget child)=>AppCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:12),child]));
  Widget _counter(BuildContext context,IconData icon,String label,String value)=>Expanded(child:Column(children:[Icon(icon),const SizedBox(height:5),Text(value,style:const TextStyle(fontWeight:FontWeight.bold)),Text(label,style:Theme.of(context).textTheme.bodySmall)]));
  Widget _stat(BuildContext context,String value,String label)=>Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(value,style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.bold)),Text(label,style:Theme.of(context).textTheme.bodySmall)]));
}
