import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../services/theme_service.dart';
class ThemeEditResult{final ThemeSettings settings;final ThemeMode mode;ThemeEditResult(this.settings,this.mode);}
class ThemeScreen extends StatefulWidget{final ThemeSettings initialSettings;final ThemeMode initialMode;const ThemeScreen({super.key,required this.initialSettings,required this.initialMode});@override State<ThemeScreen> createState()=>_ThemeScreenState();}
class _ThemeScreenState extends State<ThemeScreen>{late ThemeSettings settings;late ThemeMode mode;static const colors=<Color>[Color(0xFFF7F5FA),Color(0xFFE8F5E9),Color(0xFFE3F2FD),Color(0xFFFFF3E0),Color(0xFFFCE4EC),Color(0xFFEDE7F6),Color(0xFFE0F2F1),Color(0xFFFFFDE7),Color(0xFF263238),Color(0xFF37474F),Color(0xFF3F51B5),Color(0xFF00695C)];@override void initState(){super.initState();settings=widget.initialSettings;mode=widget.initialMode;}
 Future<void> _save(ThemeSettings next)async{setState(()=>settings=next);await ThemeService.save(next);}
 Future<void> _mode(ThemeMode m)async{final p=await SharedPreferences.getInstance();await p.setString('theme_mode',m==ThemeMode.dark?'dark':m==ThemeMode.light?'light':'system');if(mounted)setState(()=>mode=m);}
 Future<void> _pickImage()async{final p=await ThemeService.pickAndPersistImage();if(p!=null&&mounted)await _save(settings.copyWith(imagePath:p));}
 Future<void> _clearImage()async=>_save(settings.copyWith(clearImagePath:true));
 @override Widget build(BuildContext context){final has=settings.imagePath!=null;return Scaffold(appBar:AppBar(title:const Text('Personalizar tema'),leading:IconButton(icon:const Icon(Icons.close),onPressed:()=>Navigator.pop(context))),body:ListView(padding:const EdgeInsets.all(16),children:[Text('Modo do aplicativo',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:8),SegmentedButton<ThemeMode>(segments:const[ButtonSegment(value:ThemeMode.system,label:Text('Sistema'),icon:Icon(Icons.settings_brightness_outlined)),ButtonSegment(value:ThemeMode.light,label:Text('Claro'),icon:Icon(Icons.light_mode_outlined)),ButtonSegment(value:ThemeMode.dark,label:Text('Escuro'),icon:Icon(Icons.dark_mode_outlined))],selected:{mode},onSelectionChanged:(s)=>_mode(s.first)),const SizedBox(height:24),Text('Cor de fundo',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:12),Wrap(spacing:12,runSpacing:12,children:colors.map((c){final selected=!has&&settings.backgroundColorValue==c.value;return InkWell(onTap:()=>_save(settings.copyWith(backgroundColorValue:c.value,clearImagePath:true)),borderRadius:BorderRadius.circular(18),child:AnimatedContainer(duration:const Duration(milliseconds:150),width:52,height:52,decoration:BoxDecoration(color:c,borderRadius:BorderRadius.circular(18),border:Border.all(color:selected?Theme.of(context).colorScheme.primary:Colors.black12,width:selected?3:1)),child:selected?Icon(Icons.check,color:c.computeLuminance()>.55?Colors.black:Colors.white):null));}).toList()),const SizedBox(height:28),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Foto personalizada',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:8),Text(has?'Sua foto está aplicada ao fundo.':'Escolha uma foto da galeria para usar como fundo.'),const SizedBox(height:12),FilledButton.icon(onPressed:_pickImage,icon:const Icon(Icons.photo_library_outlined),label:Text(has?'Trocar foto':'Usar minha foto')),if(has)...[TextButton.icon(onPressed:_clearImage,icon:const Icon(Icons.close),label:const Text('Remover foto')),_slider('Zoom',settings.scale,.5,3,(v)=>settings.copyWith(scale:v)),_slider('Posição horizontal',settings.x,-5,5,(v)=>settings.copyWith(x:v)),_slider('Posição vertical',settings.y,-5,5,(v)=>settings.copyWith(y:v)),_slider('Transparência da foto',settings.opacity,.05,1,(v)=>settings.copyWith(opacity:v))]]))),const SizedBox(height:12),const Card(child:ListTile(leading:Icon(Icons.info_outline),title:Text('Tema salvo automaticamente'),subtitle:Text('As configurações permanecem após fechar e abrir o Polirotinas.')))]));}
 Widget _slider(String label,double value,double min,double max,ThemeSettings Function(double) next)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(label),Text(value.toStringAsFixed(2))]),Slider(value:value,min:min,max:max,divisions:20,onChanged:(v)=>_save(next(v)))]);
}